[project]
name = "weatherforecast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fakeredis>=2.37.0",
    "fastapi>=0.139.2",
    "joblib>=1.5.3",
    "locust>=2.46.2",
    "meteostat>=2.1.4",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "redis>=8.0.1",
    "scikit-learn>=1.9.0",
    "uvicorn>=0.51.0",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
