apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
spec:
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
      annotations:
        rollout/id: "{{ uuidv4 }}" 
    spec:
      containers:
      - name: fastapi-app
        image: "weather-backend:latest"
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://weather-redis:6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "512Mi"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: weather-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weather-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50